
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    -   id: mypy

  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: python -m pytest
        language: conda
        types: [python]
        pass_filenames: false
        stages:
          - pre-commit