services:
  pipeline:
    container_name: airflow
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${AIRFLOW_USERNAME}
        - PASSWORD=${AIRFLOW_PASSWORD}
        - EMAIL=${AIRFLOW_EMAIL}
    volumes:
      - .:/data
    restart: unless-stopped
