services:
  pipeline:
    container_name: airflow
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=${AIRFLOW_USERNAME}
        - PASSWORD=${AIRFLOW_PASSWORD}
        - EMAIL=${AIRFLOW_EMAIL}
    volumes:
      - ./data:/home/airflow/data
      - ./dags:/opt/airflow/dags
    environment:
      - PYTHONPATH=/home/airflow/project
      - TARGET_FOLDER=/home/airflow/data
      - TZ=America/Sao_Paulo
      - PYTZDATA_TZDATADIR=/usr/share/zoneinfo
    restart: unless-stopped
