name: quantum-ai
channels:
    - conda-forge
dependencies:
    - pip
    - python=3.12
    - pip:
      - numpy
      - qiskit
      - tqdm
      - matplotlib
      - pylatexenc
      - qiskit-ibm-runtime
      - qiskit_qasm3_import
      - Pillow
      - qiskit-aer
      - torch
      - torchvision
      - h5py
      - polars
      - apache-airflow==2.11.0
      - apache-airflow-providers-standard
      - psycopg2-binary
      - kagglehub
      - huggingface_hub
      - pandas
      - ruff
      - tox
      - mypy
      - types-tqdm
      - pytest
      - lark
platforms:
  - linux-64
